name: Build & Deploy

on:
  push:
    branches:
      - main
env:          
  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}

  
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        # uses: actions/checkout@v2
        run: echo "hello world $SSH_USERNAME"
        

      - name: Print SSH Username
        run: |
          echo "SSH Username: ${{ secrets.SSH_USERNAME }}"

      # - name: Deploy HTML file
      #   run: |
      #     rsync -avz --delete ./ iamgak@${{ secrets.HOST_IP }}:/home/iamgak/demo
      #   env:
      #     SSH_KEY: ${{ secrets.SSH_KEY }}
      #   shell: bash
